config/routes.rb
Rails.application.routes.draw do
  get "users/profile"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :portfolios do
    resources :assets
  end

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end

  get "/u/:id", to: "users#profile", as: "user"
  get "about", to: "pages#about"
  get "portfolios", to: "porfolios#index"
  get "posts", to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  has_many :assets, dependent: :destroy
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]
  # before_action :set_portfolio

  # GET /portfolios or /portfolios.json
  def index
    @portfolios = []
    @example_portfolio = Portfolio.count > 0 ? Portfolio.first : Portfolio.new
  end

  # GET /portfolios/1 or /portfolios/1.json
  def show
    @mv = 0.0
    @new_mv = 0.0
    @transactions = []
    @assets = @portfolio.assets.order(created_at: :asc)
    @assets.each do |asset|
      stock = StockService.new(asset.ticker)
      asset.price = stock.price
      asset.name = stock.name
      @mv += asset.price * asset.quantity
      asset.save!
    end

    if @portfolio.pending_contribution != 0 && !@portfolio.pending_contribution.nil?
      @new_mv = @mv + @portfolio.pending_contribution
      @portfolio.assets.each do |asset|
        # Calculate rebalance transactions here
        desired_mv = @new_mv * (asset.desired_weight/100.0)
        desired_qty = (desired_mv/asset.price).floor
        qty_diff = desired_qty - asset.quantity
        if qty_diff != 0
          txn_hash = {
            "ticker" => asset.ticker,
            "direction" => qty_diff > 0 ? "BUY" : "SELL",
            "quantity" => qty_diff.abs,
            "new_weight" => desired_mv / @new_mv
          }
          @transactions.push(txn_hash)
        end
      end
    end
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios or /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)
    # @portfolio.user = current_user

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: "Portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1 or /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1 or /portfolios/1.json
  def destroy
    @portfolio.destroy!

    respond_to do |format|
      format.html { redirect_to portfolios_path, status: :see_other, notice: "Portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @colors = ["#291f43", "#483775", "#674ea7", "#9583c1", "#c2b8dc"]
      @portfolio = Portfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :pending_contribution)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio) do |form| %>
  <% if portfolio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
        <% portfolio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div id="<%= dom_id portfolio %>" class="card border-0">
  <div class="card-body px-0">
    <h2 class="card-title mb-4 <%= example ?  "" : "text-center"  %>">
      <%= example ? "Example Portfolio" : portfolio.name %>
    </h2>
    <% if !showDetail %>
      <p class="card-text">
        <%= portfolio.assets.map{ |asset| "#{asset.ticker} (#{asset.desired_weight.to_s}%)"}.join(" | ") %>
      </p>
    <% else %>
      <div class="row my-4">
        <h4 class="text-center">Market Value: <%= number_to_currency(@mv) %></h4>
      </div>
      <div class="row my-4">
        <div class="col-6">
          <h5 class="text-center">Holdings</h5>
          <div class = "col">
            <div class="accordion" id="assetAccordion">
              <% portfolio.assets.each_with_index do |asset, i| %>
                <div class="accordion-item">
                  <h5 class="accordion-header">
                    <button class="acc-btn accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%="#{i}"%>" aria-expanded="true" aria-controls="collapse<%="#{i}"%>" >
                      <span>
                        <%= "#{asset.name} (#{asset.ticker})" %>
                      </span>
                      <strong>
                        <%= number_to_currency(asset.quantity * asset.price) %>
                      </strong>
                    </button>
                  </h5>
                  <div id="collapse<%="#{i}"%>" class="accordion-collapse collapse show" aria-expanded="true">
                    <div class="accordion-body">
                      <div class="row">
                        <span> Quantity: <strong> <%= asset.quantity || 0.0 %> </strong></span>
                      </div>
                      <div class="row">
                        <span> Current Price: <strong><%= number_to_currency(asset.price) %></strong></span>
                      </div>
                      <div class="row">
                        <span> Current Weight: <strong><%= sprintf("%.2f", 100 * asset.quantity * asset.price / @mv) %>% </strong></span>
                      </div>
                      <div class="row">
                        <span> Stray: <strong> <%= sprintf("%.2f", 100 * asset.quantity * asset.price / @mv - asset.desired_weight) %>% </strong></span>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="col-6 justify-content-center">
          <h5 class="text-center">Target Allocation</h5>
          <%= pie_chart(portfolio.assets.map { |asset| [asset.ticker, asset.desired_weight] }, label: "Desired Allocation", height: "500px", suffix: "%", colors: @colors) %>
        </div>
      </div>

      <%= form_with model: portfolio do |form| %>
        <div class="row mt-4 justify-content-center">
          <div class="col-6 text-center">
                <%= form.label "Enter contribution value: $" %>
                <%= form.number_field :pending_contribution, step: 0.01, value: '%.2f' % portfolio.pending_contribution %>
          </div>
        </div>
            
        <div class="row mt-4 justify-content-center">
          <div class="d-grid col-4">
                <%= form.submit "Calculate Transactions", class: 'mb-2 btn btn-success', remote: true %>
          </div>
        </div>
      <% end %>

      <% if @transactions.length() > 0 %>
        <h5 class="text-center mt-4">Rebalance Transactions</h5>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Ticker</th>
              <th scope="col">Direction</th>
              <th scope="col">Quantity</th>
              <th scope="col">New Weight</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |t| %>
              <tr>
                <th scope="row"><%= t["ticker"] %></th>
                <td><%= t["direction"] %></td>
                <td><%= t["quantity"] %></td>
                <td><%= sprintf("%.2f", 100 * t["new_weight"]) %>%</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

<style>
.accordion {
    --bs-accordion-active-color: #fff; /* Sets the text color. */
    --bs-accordion-active-bg: #674ea7; /* Sets the background color. */
}
</style>

app/views/portfolios/edit.html.erb
<% content_for :title, "Editing portfolio" %>

<h1>Editing portfolio</h1>

<%= render "form", portfolio: @portfolio %>

<br>

<div>
  <%= link_to "Show this portfolio", @portfolio %> |
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<div class="container my-4">
  <h1>Portfolio Rebalancer</h1>

  <div class="mt-4 mb-2">
    <%= render @example_portfolio, example: true, showDetail: false %>
  </div>
  <div class="btn-group" role="group" aria-label="Post Actions">
    <%= link_to @example_portfolio, :class => "btn btn-primary" do %>
      <i class="bi bi-eye-fill"></i> Test it out
    <% end %>
  </div>
  
  <br/>

  <% if false %> <%# to do %> 
  <%= link_to new_portfolio_path, :class => "btn btn-success my-5" do %>
    <i class="bi bi-plus-circle-fill"></i> Create a new portfolio
  <% end %>
  <% end %>

  <%#div id="portfolios">
    <%# @portfolios.each do |portfolio| %>
      <%#= render portfolio, showDetail: false %>
      <%#div class="btn-group mt-2 mb-4" role="group" aria-label="Post Actions">
        <%#= link_to portfolio, :class => "btn btn-primary" do %>
          <%#i class="bi bi-eye-fill"></i> Show
        <%# end %>
      <%#/div>
    <%# end %>
  <%#/div>
</div> %>

app/views/portfolios/new.html.erb
<% content_for :title, "New portfolio" %>

<h1>New portfolio</h1>

<%= render "form", portfolio: @portfolio %>

<br>

<div>
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<div class="container my-4">
  <%# <div class="row"> %>
    <%# <div class="col-sm p-0"> %>
      <%#= link_to portfolios_path, :class => "btn btn-secondary mb-2" do %>
        <%# <i class="bi bi-chevron-double-left"></i> Back %>
      <%# end %>
    <%# </div> %>
  <%# </div>  %>

  <div class="row my-2">
    <%= render @portfolio, example: false, showDetail: true %>
  </div>

  <% if current_user && current_user.id == @portfolio.user_id %>
  <div class="row">
    <div class="col-sm">
      <%= link_to edit_portfolio_path(@portfolio), :class => "btn btn-primary mb-2" do %>
        <i class="bi bi-pencil-fill"></i> Edit
      <% end %> 
      <%= button_to @portfolio, method: :delete, :class => "btn btn-danger mb-2", form_class: "inlineButton" do %>
        <i class="bi bi-trash-fill"></i> Delete
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<% if @assets.reduce(0) { |sum, asset| sum + asset.desired_weight} != 100 %>
  <div class="container my-4">
    <div class="row">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Add Asset</h3>
          <div class="card-text">
            <%= render 'assets/form', portfolio: @portfolio %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>