config/routes.rb
Rails.application.routes.draw do
  get "users/profile"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :portfolios do
    resources :assets
  end

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end

  get "/u/:id", to: "users#profile", as: "user"
  get "about", to: "pages#about"
  get "portfolios", to: "porfolios#index"
  get "posts", to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5, maximum: 50}
  validates :body, presence: true, length: {minimum: 10, maximum: 1000}
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div >
  <div  id="<%= dom_id post %>" class="card">
    <div class="card-body">
      <h2 class="card-title">
        <%= post.title %>
      </h2>
      <h5 class="mb-3">
        Posted by <%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user.id) %>
      </h5>
      <h6 class="card-subtitle mb-2 text-body-secondary">
        <%= pluralize(post.views, "view") %>
      </h6>
      <p class="card-text">
        <%= post.body %>
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container my-4">
  <h1>Posts</h1>

  <%= link_to new_post_path, :class => "btn btn-success mb-4" do %>
    <i class="bi bi-plus-circle-fill"></i> New Post
  <% end %>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <div class="btn-group mt-2 mb-4" role="group" aria-label="Post Actions">
        <%= link_to post, :class => "btn btn-primary" do %>
          <i class="bi bi-eye-fill"></i> Show
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div>
  
 <% content_for :title, "New post" %>

  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class ="row">
    <div class="col-sm">
      <%= link_to posts_path, :class => "btn btn-secondary mb-2" do %>
        <i class="bi bi-chevron-double-left"></i> Back
      <% end %>
    </div>
  </div>

  <div class="row my-2">
    <%= render @post %>
  </div>

  <% if current_user && current_user.id == @post.user_id %>
  <div class="row">
    <div class="col-sm">
      <%= link_to edit_post_path(@post), :class => "btn btn-primary mb-2" do %>
        <i class="bi bi-pencil-fill"></i> Edit
      <% end %> 
      <%= button_to @post, method: :delete, :class => "btn btn-danger mb-2", form_class: "inlineButton" do %>
        <i class="bi bi-trash-fill"></i> Delete
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<div class="container">
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', post: @post, comment: comment %>
    <% end %>
    <%= render 'comments/form', post: @post %>
</div>